name: 镜像构建模版

on:
  workflow_call:
    inputs:
      image-authors:
        default: 'Bromine0x23 <bromine0x23@gmail.com>'
        required: false
        type: string
      image-title:
        required: true
        type: string
      image-version:
        required: true
        type: string
      image-build-context:
        default: '.'
        required: false
        type: string
      image-build-args:
        required: false
        type: string
      image-build-platforms:
        default: linux/amd64,linux/arm64
        required: false
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        default: ''
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  
jobs:
  image-build-job:
    runs-on: ubuntu-latest
    steps:
    - id: setup
      name: 设置
      run: |
        {
          echo 'IMAGE_TAGS<<EOF'
          for NAME in ${{ inputs.image-name }}; do
            for TAG in ${{ inputs.image-tag }}; do
              echo "${NAME}:${TAG}"
            done
          done
          echo EOF
        } >> "$GITHUB_ENV"
    - id: checkout
      name: 检出代码
      uses: actions/checkout@v4
    - id: setup_qemu
      name: 设置 QEMU
      uses: docker/setup-qemu-action@v3
    - id: setup_buildx
      name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3
    - id: login_dockerhub
      name: 登录 Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: login_ghcr
      name: 登录 GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: build_push
      name: 构建及发布镜像
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.image-build-context }}
        build-args: ${{ inputs.image-build-args }}
        labels: |
          org.opencontainers.image.authors="${{ inputs.image-authors }}"
          org.opencontainers.image.title="${{   inputs.image-title   }}"
          org.opencontainers.image.version="${{ inputs.image-version }}"
        platforms: ${{ inputs.image-build-platforms }}
        push: true
        tags: ${{ env.IMAGE_TAGS }}
    # - id: trivy
    #   name: 漏洞扫描
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: '${{ env.IMAGE_REPOSITORY_DOCKERHUB }}:${{ inputs.image-tag }}'
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'
    #     ignore-unfixed: true
    #     format: 'table'