name: OracleLinux 镜像

on:
  push:
    branches:
    - main
    paths:
    - oraclelinux/**
    - '!oraclelinux/README.md'
    - .github/workflows/image-build.yml
    - .github/workflows/oraclelinux.yml
  schedule:
  - cron:  '0 8 1 * *'

jobs:
  oraclelinux:
    uses: ./.github/workflows/image-build.yml
    name: OracleLinux
    strategy:
      matrix:
        oraclelinux-version: [9, 8, 7]
        is-slim: [false, true]
        include:
        - oraclelinux-latest-version: 9
        - oraclelinux-version: 9
          dnf: microdnf
        - oraclelinux-version: 8
          dnf: microdnf
    with:
      image-label-title: OracleLinux
      image-label-description: OracleLinux 系统基础镜像
      image-label-version: "${{ matrix.oraclelinux-version }}"
      image-build-context: ./oraclelinux/${{ matrix.oraclelinux-version }}
      image-build-args: |
        BASE_IMAGE=oraclelinux:${{ matrix.oraclelinux-version }}-slim
        IS_SLIM=${{ matrix.is-slim && 'slim' || '' }}
        ${{ matrix.dnf && format('DNF={0}', matrix.dnf) || '' }}
      image-name: >-
        bromine0x23/oraclelinux
        ghcr.io/bromine0x23/oraclelinux
      image-tag: >-
        ${{ matrix.oraclelinux-version }}${{ matrix.is-slim && '-slim' || '' }}
        ${{ matrix.oraclelinux-version == matrix.oraclelinux-latest-version && (matrix.is-slim && 'slim' || 'latest') || '' }}
    secrets: inherit